Gabin dev
EBM2018/teamy pull request #70
Opened 2019-03-19 10:42 UTC by gvallet

- Création d'un compte pour un utilisateur
- Connexion d'un utilisateur ayant déjà un compte
- Génération d'un token pour l'utilisateur connecté
- Vérification de l'authenticité du token (pas terminé, en cours de dev)

2019-03-19 17:39 UTC, Nathanmalnoury requested changes
Commence par : 
- [ ] Résoudre le conflit de backend/src/services/user/model.js
- [ ] remettre ton eslint, tu ne passeras pas travis sans ça, je te mets son erreur en bas
- [ ] répondre aux remarques que je t'aies faite, toute ne veulent pas forcément dire que ce que tu as fait est à refaire.

Tant que ton ```$ npm test``` en local ne passeras pas, travis bloquera
```
$ npm test
> filrouge-boilerplate-backend@1.0.0 test /home/travis/build/EBM2018/teamy/backend
> eslint src/
Oops! Something went wrong! :(
ESLint: 5.12.1.
ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:
    eslint --init
ESLint looked for configuration files in /home/travis/build/EBM2018/teamy/backend/src/api and its ancestors. If it found none, it then looked in your home directory.
If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint
```

2019-03-19 17:39 UTC, Nathanmalnoury commented on backend/private.key
> +-----BEGIN RSA PRIVATE KEY-----
:warning: Devrait pas être sur le git

2019-03-19 17:39 UTC, Nathanmalnoury commented on backend/src/api/resources/auth/authController.js
> +    // A quoi sert le next ?
Pour le middleware, s'il vient apres la fonction createUser

2019-03-19 17:39 UTC, Nathanmalnoury commented on backend/src/api/resources/auth/authController.js
> +        isProf: false,
Et si c'est un Prof ? 
Pas le meme portail ?

2019-03-19 17:39 UTC, Nathanmalnoury commented on backend/src/services/auth/createToken.js
> +    //     // clé de hashage utilisée par défaut : HS256, mais clé symétrique
On ne met pas d'accent dans le code

2019-03-19 17:39 UTC, Nathanmalnoury commented on backend/src/services/user/model.js
> +  email: {
Tu n'es pas à jour du master, ces champs existent, mais portent des noms différents.
- mailAddress
- hashPassword 
- Salt
Tu dois rebase avant de faire un pull request

2019-03-19 17:39 UTC, Nathanmalnoury commented on v0.0.3/groupeAuto.html
> +<!DOCTYPE html>
Est-ce que c'est la page d'identification ? 
-> si oui, dans le front, 
-> sinon l'enlever

2019-03-19 17:39 UTC, Nathanmalnoury commented on v0.0.3/groupeAuto.js
> +var nomClasse= document.cookie;
Idem, soit dans le front, soit dans le back, tu ne crois pas ?

2019-03-19 17:39 UTC, Nathanmalnoury commented on v0.0.3/mock_authentification.js
> +var authent=true;
idem front ou back ?
ou encore un nouveau dossier /mock_data ?

2019-03-19 17:39 UTC, Nathanmalnoury commented on v0.0.3/traitementListe.js
> +let csvToJson=require('convert-csv-to-json');
ça ressemble à du back... 
Dans le dossier /backend/utilities ?

2019-03-20 08:26 UTC, gvallet commented on backend/src/api/resources/auth/authController.js
> +        isProf: false,
Si ça sera le même portail je pense mais faudra que je gère les permissions, je pensais à une case à cocher et derrière faut que ça soit validé par l'admin

2019-03-26 09:29 UTC, Nathanmalnoury commented on backend/private.key
> +-----BEGIN RSA PRIVATE KEY-----
A enlever du coup

2019-03-26 09:29 UTC, Nathanmalnoury commented on backend/src/services/user/model.js
>    salt: {
supprime carrément cet objet si elle ne sert à rien ! :)

2019-03-26 09:29 UTC, Nathanmalnoury commented on backend/src/api/resources/auth/authController.js
> +    <h1> Test création form </h1>
ça ressembla à du front non ?
- A mettre dans le front si ça en est (vois avec la team front), 
- sinon : ne prend pas cette remarque en compte 😛

2019-03-26 09:29 UTC, Nathanmalnoury commented on backend/README.md
> +<<<<<<< HEAD
Appelle ton fichier différemment, parce que tu écris sur le ReadMe dont l'objectif est dire aux autres comment lancer le back

2019-03-26 10:27 UTC, nymous commented
Mettre une clé privée sur Github :ok_hand: (en vrai c'est dur de gérer des secrets ^^)

2019-03-26 10:51 UTC, gvallet commented
Je sais j'ai vu ;) mais du coup je suis passé par un secret, et j'essaie de
faire en sorte qu'elle passe pas sur Github.

Le mar. 26 mars 2019 à 11:27, Thomas Gaudin <notifications@github.com> a
écrit :

> Mettre une clé privée sur Github 👌 (en vrai c'est dur de gérer des
> secrets ^^)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/EBM2018/teamy/pull/70#issuecomment-476563256>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ApjvxEgGSY_tXpChvbs8VVNshmAC1yToks5vafYrgaJpZM4b7zks>
> .
>

2019-03-27 09:06 UTC, Nathanmalnoury approved these changes

2019-03-27 09:14 UTC, merged